version: "3"
networks:
  default:
    driver: bridge
services:
  #---------------------------------------------------------#
  # THIS IS NOT A SERVICE:
  # Just a template for internal variable references.
  #---------------------------------------------------------#
  not-a-service:
    build:
      args: &ref_build_args
        WD: "$WD"
        WHALES_PROJECT_NAME: "$WHALES_PROJECT_NAME"
        WHALES_SELECTED_SERVICE: "$WHALES_SELECTED_SERVICE"
        WHALES_SETUP_PATH: "$WHALES_SETUP_PATH"
        WHALES_ENTRY_SCRIPT: "$WHALES_ENTRY_SCRIPT"
  #---------------------------------------------------------#
  # SERVICE: Hello World
  #---------------------------------------------------------#
  hello-service:
    image: whales-hello:build
    build:
      context: ".." # !!! important !!! Context = root of project.
      dockerfile: "${WHALES_SETUP_PATH}/Dockerfile"
      args:
        <<: *ref_build_args
    # volumes:
    #   - ./../HELLO_WORLD:$WD/HELLO_WORLD:rw  ## <- r/w   allows for live developing
    command:
      [ "/bin/bash", "-c", "echo -e \"Service \\033[1mhello-service\\033[0m built with image \\033[1mwhales-hello:build\\033[0m.\"" ]
