version: "3"
networks:
  default:
    driver: bridge
services:
  # !!! Your services here !!! #
  ### EXAMPLES:
  # #---------------------------------------------------------#
  # # SERVICE: Production
  # #---------------------------------------------------------#
  # prod-service:
  #   image: prod:build
  #   build:
  #     context: "."
  #     dockerfile: "${WHALES_SETUP_PATH}/Dockerfile"
  #     args: &ref_build_args
  #         WD: "$WD"
  #   volumes: &ref_volume_args
  #     - ./../logs:$WD/logs:rw   ## <- (r/)w for logging between all docker levels.
  #     - ./../src:$WD/src:rw     ## <- r/w   allows for live developing
  #     - ./../test:$WD/test:rw   ##          ""
  #     - ./../data:$WD/data:rw   ## <- r/w   data folder, images will be stored here.
  #     - ./../dist:$WD/dist:rw   ## <- r/w   distribution folder, VERSION + Programme artefacts.
  #     - ./../build:$WD/build:rw ## <- (r/)w build folder -> artefacts
  #   command:
  #     [ "/bin/bash", "-c", "echo -e \"Service built.\"" ]
  # #---------------------------------------------------------#
  # # SERVICE: Test
  # #---------------------------------------------------------#
  # test-service:
  #   image: test:build
  #   build:
  #     context: "."
  #     dockerfile: "${WHALES_SETUP_PATH}/Dockerfile"
  #     args:
  #       <<: *ref_build_args
  #   volumes: *ref_volume_args
  #   command:
  #     [ "/bin/bash", "-c", "echo -e \"Service built.\"" ]
