version: "3"
networks:
  default:
    driver: bridge
services:
  #---------------------------------------------------------#
  # SERVICE: Hello World
  #---------------------------------------------------------#
  hello-service:
    image: hello:build
    build:
      context: "."
      dockerfile: ".whales.Dockerfile"
      args:
        WD: "/usr/app/whales"
    # volumes:
    #   - ./HELLO_WORLD:$WD/HELLO_WORLD:rw  ## <- r/w   allows for live developing
    command:
      [ "/bin/bash", "-c", "echo -e \"Service built.\"" ]
