version: "3"
networks:
  default:
    driver: bridge
services:
  #---------------------------------------------------------#
  # THIS IS NOT A SERVICE:
  # Just a template for internal variable references.
  #---------------------------------------------------------#
  not-a-service:
    build:
      context: .
      args: &ref_build_args
        WD: "$WD"
        WHALES_PROJECT_NAME: "$WHALES_PROJECT_NAME"
        WHALES_SELECTED_SERVICE: "$WHALES_SELECTED_SERVICE"
        WHALES_SETUP_PATH: "$WHALES_SETUP_PATH"
        WHALES_ENTRY_SCRIPT: "$WHALES_ENTRY_SCRIPT"

  #################################################################
  # !!! Your services here !!!
  # - Ensure usage of `<<: *ref_build_args` in `build > args`.
  # - Ensure the `context:` argument is correctly relativised.

  ### EXAMPLES:
  # #---------------------------------------------------------#
  # # SERVICE: Production
  # #---------------------------------------------------------#
  # prod-service:
  #   image: prod:build
  #   build:
  #     context: ".."
  #     dockerfile: "${WHALES_SETUP_PATH}/Dockerfile"
  #     args:
  #       <<: *ref_build_args
  #   volumes:
  #     - ./../logs:$WD/logs:rw   ## <- (r/)w for logging between all docker levels.
  #     - ./../src:$WD/src:rw     ## <- r/w   allows for live developing
  #     - ./../test:$WD/test:rw   ##          ""
  #     - ./../data:$WD/data:rw   ## <- r/w   data folder, images will be stored here.
  #     - ./../dist:$WD/dist:rw   ## <- r/w   distribution folder, VERSION + Programme artefacts.
  #     - ./../build:$WD/build:rw ## <- (r/)w build folder -> artefacts
  #   command:
  #     [ "/bin/bash", "-c", "echo -e \"Service \\033[1mprod-service\\033[0m built with image \\033[1mwhales-prod:build\\033[0m.\"" ]
  # #---------------------------------------------------------#
  # # SERVICE: Test
  # #---------------------------------------------------------#
  # test-service:
  #   image: test:build
  #   build:
  #     context: ".."
  #     dockerfile: "${WHALES_SETUP_PATH}/Dockerfile"
  #     args:
  #       <<: *ref_build_args
  #   volumes:
  #     - ./../logs:$WD/logs:rw   ## <- (r/)w for logging between all docker levels.
  #     - ./../src:$WD/src:rw     ## <- r/w   allows for live developing
  #     - ./../test:$WD/test:rw   ##          ""
  #     - ./../data:$WD/data:rw   ## <- r/w   data folder, images will be stored here.
  #     - ./../dist:$WD/dist:rw   ## <- r/w   distribution folder, VERSION + Programme artefacts.
  #     - ./../build:$WD/build:rw ## <- (r/)w build folder -> artefacts
  #   command:
  #     [ "/bin/bash", "-c", "echo -e \"Service \\033[1mtest-service\\033[0m built with image \\033[1mwhales-test:build\\033[0m.\"" ]
