version: "3"
networks:
  default:
    driver: bridge
services:
  #---------------------------------------------------------#
  # Test
  #---------------------------------------------------------#
  test-service:
    image: polarwhales-test:build
    build:
      context: ".." # !!! important !!! Context = root of project.
      dockerfile: whales_setup/Dockerfile
      args:
        WD: "$WD"
        ENTRY_SCRIPT: "$ENTRY_SCRIPT"
    volumes:
      # - ./../logs:$WD/logs:rw   ## <- (r/)w for logging between all docker levels.
      - ./../src:$WD/src:rw     ## <- r/w   allows for live developing
      - ./../test:$WD/test:rw   ##          ""
    command:
      ["bash", "-c", "echo -e \"Service \\033[1mtest-service\\033[0m built with image \\033[1mpolarwhales-test:build\\033[0m.\""]
