#!/usr/bin/env bash

##############################################################################
# DESCRIPTION:
# Script to automate import of whales tool into a given project.
##############################################################################

#######################################
# Global vars
#######################################

SCRIPTARGS="$@";
FLAGS=( "$@" );
OUT="/dev/stdout";
ERR="/dev/stderr";
VERBOSE="/dev/null";
VERSION="";

#######################################
# Methods
#######################################

# Create temporary folder
function set_temporary_folder() {
    local name="tmp";
    local path;
    local k=0;
    while [[ -d "${name}_${k}" ]] || [[ -f "${name}_${k}" ]]; do k=$(( $k + 1 )); done;
    path="${name}_${k}";
    mkdir "$path" && echo "${path}";
}

function import_whales_files() {
    local flag_force=$1;
    local flag_templates=$2;
    local flag_examples=$3;
    local path="$4";

    # Allow the following to be overwritten
    [[ -d ".whales" ]] && rm -rf ".whales";
    [[ -d ".whales.templates" ]] && rm -rf ".whales.templates";
    [[ -d ".whales.examples"  ]] && rm -rf ".whales.examples";
    # Copy the rest to destination:
    cp -r "${path}/src"                               "./.whales";
    ( $flag_templates ) && cp -r "${path}/templates"  "./.whales.templates";
    ( $flag_examples )  && cp -r "${path}/examples"   "./.whales.examples";
    local flag_copy="-n";
    ( $flag_force ) && flag_copy="";
    cp $flag_copy "${path}/config/.whales.env"                 ".";
    cp $flag_copy "${path}/config/.whales.Dockerfile"          ".";
    cp $flag_copy "${path}/config/.whales.docker-compose.yml"  ".";

    # Output version:
    VERSION="$( cat ${path}/dist/VERSION 2> $VERBOSE || echo "{${tag}}" )";
    # Cleanup
    rm -rf "${dest_temp}";
}

# Obtain artefact from Git repository
function get_artefact_from_repo() {
    local url_info="https://github.com/RLogik/whales/releases";
    [ "$4" == "" ] && echo -e "Usage: \033[1mimportwhales [--force] [--templates] [--examples] {TAG}\033[0m. Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
    !( check_curl && check_tar ) && echo -e "You need \033[1mcurl\033[0m and \033[1mtar\033[0m in order to be able to use this command." >> $ERR && exit 1;
    local flag_force=$1;
    local flag_templates=$2;
    local flag_examples=$3;
    local tag="$( echo "$4" | sed -E "s/^v([[:digit:]]+.*)$/\1/gi" )";
    local file="whales.tar.gz";
    local url="https://github.com/RLogik/whales/archive/refs/tags";         # scheme: {url}/{tag}.tar.gz
    # local url="https://codeload.github.com/RLogik/whales/tar.gz/refs/tags"; # scheme: {url}/{tag}
    local success=false;
    local dest_temp="$( set_temporary_folder )";

    # Download zip archive from repository:
    local urls=( "${url}/${tag}.tar.gz" "${url}/v${tag}.tar.gz" );
    local url_;
    for url_ in "${urls[@]}"; do
        curl -L "${url_}" -o "${dest_temp}/${file}" 2> $VERBOSE >> $VERBOSE \
            && tar -xzf "${dest_temp}/${file}" --directory "${dest_temp}" 2> $VERBOSE >> $VERBOSE \
            && success=true && break;
    done
    ! ( $success ) && echo -e "Tagname \033[1m${tag}\033[0m could not be found! Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && rm -rf "${dest_temp}" && exit 1;

    local path="$( ls -d ${dest_temp}/*/ 2> $VERBOSE | head -1 | sed -E "s/\/$//" )";
    import_whales_files $flag_force $flag_templates $flag_examples "${path}";
}

# Obtain artefact via docker
function get_artefact_via_docker() {
    local url_info="https://hub.docker.com/r/rlogik/whales/tags";
    [ "$4" == "" ] && echo -e "Usage: \033[1mimportwhales [--force] [--templates] [--examples] {TAG}\033[0m. Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
    local flag_force=$1;
    local flag_templates=$2;
    local flag_examples=$3;
    local tag="$( echo "$4" | sed -E "s/^v([[:digit:]]+.*)$/\1/gi" )";
    local file="whales.tar.gz";
    local image="rlogik/whales:${tag}";
    local success=false;

    # pull from dockerhub:
    docker pull ${image} 2> $VERBOSE >> $VERBOSE && echo "${image}" && success=true;
    ! ( $success ) && echo -e "Tagname \033[1m${tag}\033[0m could not be found! Please refer to \033[94;1m${url_info}\033[0m for valid tag names." >> $ERR && exit 1;
    # Start a temporary container:
    local id="$( docker run -d "${image}" )";
    # Copy contents of application to temporary folder:
    local dest_temp="$( set_temporary_folder )";
    docker cp "${id}:/usr/app/whales/." "${dest_temp}";

    local path="${dest_temp}";
    import_whales_files $flag_force $flag_templates $flag_examples "${path}";

    # Cleanup
    docker stop "${id}" >> $VERBOSE;
    docker rm "${id}" >> $VERBOSE;
    docker rmi "${image}" >> $VERBOSE;
}

#######################################
# Auxiliary Methods
#######################################

function has_arg() {
    echo "$1" | grep -Eq "(^.*[[:space:]]|^)$2([[:space:]].*$|$)";
}

function check_curl() { ( curl --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }
function check_tar() { ( tar --version >> $VERBOSE 2> $VERBOSE ) && return 0 || return 1; }

function check_dos2unix() {
    ( dos2unix --version >> $VERBOSE 2> $VERBOSE ) && return 0;
    echo -e "To use Whales, you need to install \033[1mdos2unix\033[0m. To do so, try the instructions on one of the following pages:" >> $ERR;
    echo -e ""                                                         >> $ERR;
    echo -e "  https://command-not-found.com/dos2unix"                 >> $ERR;
    echo -e "  https://formulae.brew.sh/formula/dos2unix"              >> $ERR;
    echo -e "  https://chocolatey.org/packages/dos2unix"               >> $ERR;
    echo -e "  https://waterlan.home.xs4all.nl/dos2unix.html#DOS2UNIX" >> $ERR;
    echo -e ""                                                         >> $ERR;
    return 1;
}

function check_jq() {
    ( jq --version >> $VERBOSE 2> $VERBOSE ) && return 0;
    echo -e "To use Whales, you may wish to optionally install \033[1mjq\033[0m. To do so, try the instructions on one of the following pages:" >> $ERR;
    echo -e ""                                      >> $ERR;
    echo -e "  https://command-not-found.com/jq"    >> $ERR;
    echo -e "  https://formulae.brew.sh/formula/jq" >> $ERR;
    echo -e "  https://chocolatey.org/packages/jq"  >> $ERR;
    echo -e "  https://stedolan.github.io/jq"       >> $ERR;
    echo -e "";
    return 1;
}

#######################################
# Process CLI arguments
#######################################

TAG=""; [[ ${#FLAGS} -gt 0 ]] && TAG="${FLAGS[-1]}";
( echo "$TAG" | grep -Eq "^-+" ) && TAG="";
flag_force=false;     ( has_arg "$SCRIPTARGS" "-+(f|force)" )           && flag_force=true;
flag_templates=false; ( has_arg "$SCRIPTARGS" "-+(template|templates)" ) && flag_templates=true;
flag_examples=false;  ( has_arg "$SCRIPTARGS" "-+(example|examples)" )  && flag_examples=true;
success=0;
check_dos2unix || success=1;
check_jq;
VERSION="";
get_artefact_from_repo $flag_force $flag_templates $flag_examples "${TAG}";
# get_artefact_via_docker $flag_force $flag_templates $flag_examples "${TAG}";

echo -e "Version \033[92;1m${VERSION}\033[0m of Whales imported." >> $OUT;
exit $success;
