version: "3"
networks:
  default:
    driver: bridge
services:
  ## !!! Your services here !!!
  ## EXAMPLES:
  #---------------------------------------------------------#
  # SERVICE: Production
  #---------------------------------------------------------#
  prod-service:
    image: prod:build
    build:
      context: .
      dockerfile: .whales.Dockerfile
      args: &ref_build_args
          WD: "$WD"
    volumes:
        - ./data:$WD/data:rw
        - ./dist:$WD/dist:rw
        - ./src:$WD/src:ro
        # ## for debugging purposes only:
        # - ./scripts:$WD/scripts:ro
        # - ./logs:$WD/logs:rw
        # - ./build:$WD/build:rw
    command:
      [ "/bin/bash", "-c", "echo -e \"Service built.\"" ]
  #---------------------------------------------------------#
  # SERVICE: Test
  #---------------------------------------------------------#
  test-service:
    image: test:build
    build:
      context: .
      dockerfile: .whales.Dockerfile
      args:
        <<: *ref_build_args
        - ./test:$WD/test:ro
    volumes:
      - ./data:$WD/data:rw
      - ./dist:$WD/dist:rw
      - ./src:$WD/src:ro
      - ./test:$WD/test:ro
      # ## for debugging purposes only:
      # - ./scripts:$WD/scripts:ro
      # - ./logs:$WD/logs:rw
      # - ./build:$WD/build:rw
    command:
      [ "/bin/bash", "-c", "echo -e \"Service built.\"" ]
